# -*- coding: utf-8 -*-
"""201810698_05(04).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CqwzMrBMM8FyLGJmmS9TtXaMgQ6z5qey
"""

for i in range (2,10) :
    print("#  ",i,"단   #", end="\t")
print()

for j in range (1,10) :
    for i in range (2,10) :
        print(i,"x ", j,"= ",i*j, end="\t")
    print()