# -*- coding: utf-8 -*-
"""201810698_12-1(04).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FDsnufDaswJRbqgtwQk4G1CevtygBfhc
"""

#Self Study 12-1
#Code12-02.py의 upSpeed() 함수르르 수정하여, 속도가 150이 넘으면 최대 150으로 조절. if문 활용

class Car :
  color =""
  speed = 0
  def upSpeed(self,value):
    if value > 150 :
      value=150
    self.speed += value
  def dowmSpeed(self,value):
    self.speed -= value

myCar1=Car()
myCar1.color="Red"
myCar1.speed=0

myCar2=Car()
myCar2.color="Blue"
myCar2.speed=0

myCar3=Car()
myCar3.color="Yellow"
myCar3.speed=0

myCar1.upSpeed(30)
print("자동차1의 색상은 %s이며, 현재 속도는 %dkm입니다." %(myCar1.color,myCar1.speed))
myCar2.upSpeed(60)
print("자동차2의 색상은 %s이며, 현재 속도는 %dkm입니다." %(myCar2.color,myCar2.speed))
myCar3.upSpeed(0)
print("자동차3의 색상은 %s이며, 현재 속도는 %dkm입니다." %(myCar3.color,myCar3.speed))