# -*- coding: utf-8 -*-
"""201810698_04(04).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Zj2YWe8McJGqAHX6PjgAL2PjsG59uJW
"""

quest = int(input("1. 입력한 수식 계산   /   2. 두 정수 사이의 합계    선택 :"))

if quest == 1 :
   result1 = input("*** 수식을 입력해주세요  :")
   total1=eval(result1)
   print(total1)
elif quest == 2 :
   first = int(input("*** 첫 번쨰 숫자를 입력해주세요  :"))
   second = int(input("*** 두 번째 숫자를 입력해주세요  :"))
   def total2(first,second) :
       result2 = 0
       for i in range(first, second+1) :
           result2 = result2+i
       return result2
   result2=total2(first,second)
   print(first,"와 ",second,"사이의 합은 ",result2,"입니다.")

else :
  print("1 혹은 2를 입력해주세요.")

