# -*- coding: utf-8 -*-
"""201810698_12-3(04).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zOtNodjw939-UH8vamIC93E9miJROW6N
"""

#self-study 12-3
#1~1000, 1~100000, 1~10000000 각각의 합을 계산하는 스레드 프로그램 작성

import threading
import time

class RacingCar(threading.Thread):
    def __init__(self, n):
        super().__init__()
        self.n = n

    def run(self):
        total = sum(range(1, self.n + 1))
        print(f"1+2+3+.....+ {self.n} = {total}")
        time.sleep(0.1)

th1 = RacingCar(1000)
th2 = RacingCar(100000)
th3 = RacingCar(10000000)

th1.start()
th2.start()
th3.start()

th1.join()
th2.join()
th3.join()

