# -*- coding: utf-8 -*-
"""201810698_12-2(04).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/120kFZO0tPEHS0ZokZZUvOVsIK3W3-iVU
"""

#self-study 12-2
#car->sedan->sonata 순서로 상속되는 sonata클래스 추가

class Car :
  speed = 0
  def upSpeed(self,value):
    self.speed += value
    print("현재 속도(슈퍼 클래스): %d" %self.speed)

class Sedan(Car):
  def upSpeed(self,value) :
          self.speed += value

          if self.speed > 150:
            self.speed = 150
          print("현재 속도(서브 클래스) : %d" %self.speed)

class Sonata(Sedan) :
  pass

class Truck(Car):
  pass

sedan1, truck1, sonata1 = None, None, None

truck1 = Truck()
sedan1 = Sedan()
sonata1 = Sonata()

print("truck --> ", end="")
truck1.upSpeed(200)
print("sedan --> ", end="")
sedan1.upSpeed(200)
print("sonata --> ", end="")
sonata1.upSpeed(200)

