# -*- coding: utf-8 -*-
"""CircleCal

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V69i2zoXADprH1vaLKCXbo1Nnb23IFgj
"""

import math

rad=float(input("반지름"))
area=math.pi*rad**2
circum=math.pi*rad*2

print("넓이 :", area)
print("둘레 :", circum)

