# -*- coding: utf-8 -*-
"""inchTocm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KMHQ7jJdyINhadNk2tg2XdEMjX97AsC
"""

inch = float(input("inch"))
cm = inch * 2.54
print(cm)