# -*- coding: utf-8 -*-
"""kgToPound

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J5w7j8Vez9QQkPM8mTcYGm54d9O2YYd0
"""

kg = float(input("kg"))
pound = kg*2.20462

print(pound)